name: draw_text_ttf
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: Aclonica
      fonts:
         - asset: assets/Aclonica.ttf
  #
  # see https://flutter.io/custom-fonts/#from-packages
